#!/usr/bin/env bash

# @Aj-Seven
# url: https://github.com/Aj-Seven/bspwm-dots

infocenter(){
LOCK_FILE="$HOME/.cache/eww-dash.lock"

if [[ ! -f "$LOCK_FILE" ]]; then
	touch "$LOCK_FILE"
	eww -c $HOME/.config/bspwm/themes/blurry/widgets/ open dashboard
    #sleep 7
    #eww -c $HOME/.config/bspwm/themes/blurry/widgets/ close dashboard
else
	eww -c $HOME/.config/bspwm/themes/blurry/widgets/ close dashboard
	rm "$LOCK_FILE"
fi
}

calendar(){
LOCK_FILE="$HOME/.cache/eww-calendar.lock"

if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    eww -c $HOME/.config/bspwm/themes/blurry/widgets/ open calendar
else
    eww -c $HOME/.config/bspwm/themes/blurry/widgets/ close calendar
    rm "$LOCK_FILE"
fi
}

powermenu() {
LOCK_FILE="$HOME/.cache/eww-powermenu.lock"

if [[ ! -f "$LOCK_FILE" ]]; then
    touch "$LOCK_FILE"
    eww -c $HOME/.config/bspwm/themes/blurry/widgets/ open powermenu
else
    eww -c $HOME/.config/bspwm/themes/blurry/widgets/ close powermenu
    rm "$LOCK_FILE"
fi
}

case "$1" in
  --infocenter)
	infocenter;;
  --calendar)
	calendar;;
  --powermenu)
    powermenu;;
esac
