#!/usr/bin/bash
# @Aj-Seven
#
# Change in Between Juicy blur and black Themes...
#

changetheme() {
FILE="$HOME/.config/bspwm/.theme"

if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    echo "blurry" > $FILE
    bspc wm -r
    rm $FILE
fi
if [[ -f "$FILE" ]]; then
    touch "$FILE"
    echo "blacky" > $FILE
    bspc wm -r
    rm $FILE
fi
}

function blur() {
FILE="$HOME/.config/bspwm/.theme"

if [[ -f "$FILE" ]]; then
    rm $FILE
    echo "blurry" > $FILE
    bspc wm -r
fi
}

function black() {
FILE="$HOME/.config/bspwm/.theme"

if [[ -f "$FILE" ]]; then
    rm $FILE
    echo "blacky" > $FILE
    bspc wm -r
fi
}
case "$1" in
    --blur)
        blur;;
    --black)
        black;;
esac
